# What's New?

## COP Reform and Target Setting Tool Reform 

**Reorienting of the Cascade Tab Viral Load Coverage and Gap Analysis**, rather than ART Coverage, although both are taken into account. This year's new shift to begin setting the Cascade from Program Viral Load Suppression. This starting point will allow for country team users to build up a full cascade that will provide insight into VLS, VL Testing and how this will translate into determining the new on treatment and those returning to treatment. It will provide a full picture of the treatment ecosystem and the way in which countries understand if they will achieve 86% (95% x 95% x 95%) coverage across all three Cascades. This will allow countries that are at or close to Epidemic Control to better approach the understanding of how they will continue to sustain their 95-95-95 goals. This approach will put a greater emphasis on the Coverage Cascade as the driver of the target setting process, a direct shift from the past 5 years that have focused on the first two Cascades, and paint a picture of both VL to gap in Treatment and Testing.

## MER2.6 Changes

**Changes in line with MER 2.6.1**:

-   Integration of the new collapsed HTS modalities. For target setting there has been a collapse of many modalities to reduce the total number of targets being set, while still  maintaining an infectious disease testing approach. More insight into these modalities will be in the HTS section of the User Guide. Teams should be aware that the modality collapse is only for Target Setting. Results will be reported against all individual modalities. Teams are encouraged to put any further details in their workplans for how any particular modalities within the newly collapsed modalities are impacted.

-   Reduction of Target Setting Age Bands. The number of Cascade Age Bands has been reduced from COP22. This year teams will set Targets using the following age bands: <01, 1-9, 10-14, 15-24, 25-34, 35-49, 50+. In most target setting tabs, these are the age bands that will be present, however due to the nature of certain tabs and the already smaller scope of ages on which the prevention or treatment focuses, AGYW and OVC will retain their historic target setting age bands. 

-   Year 2 Targets. In an effort to help teams think through multi-year programmatic approach while setting detailed targets for the upcomign fiscal year. Year 2 targets will not be imported into DATIM and will only be set at a National Level with Age/Sex dissaggregates. 

## **PSNUxIM Tool Formulas**

When you received your newly generated PSNUxIM tool for the first time by generating it from the DataPack Self-Service App, you will need to scroll to the "Target Values" Section that begins in column CW and copy down the formulas populated in row 15 all the way down to the bottom of your DataPack. This will be required in order for your Roll-up column to properly populate as well as the Deduplication sections.
