---
editor_options: 
  markdown: 
    wrap: 72
---

\blandscape

# CXCA

## CXCA_SCRN

**CXCA_SCRN (N):** Number of HIV-positive women on ART screened for
cervical cancer.

```{r echo=FALSE, results='asis'}
sheet_name <- "CXCA"
section <- "CXCA_SCRN"
columns <- col_seq("F", "M")
data <- prepare_table_data(sheet_name, columns)
for (t in table_seq(data)) {
  make_table(t, section)
  }
```

### DATIM Import

The following data points will be imported into DATIM from this section:

-   **CXCA_SCRN (FY25)** $CXCA\_SCRN.T$

### Instructions

This indicator is **ONLY** **REQUIRED** for PEPFAR Cervical Cancer
Screening countries.

For countries that are **NOT REQUIRED** to report on this indicator, you
do not have to complete this section unless you plan to offer cervical
cancer-related services as per the relevant MER indicators. To remove
all cervical cancer targets, change the value in column "Targeted CXCA
Screening coverage rate (%)" to 0%.

1.  For historical context, review FY22 results, FY24 targets, and FY23
    Observed CXCA Screen Coverage rates as reported in DATIM, as well as
    FY23 Targets for TX_CURR and those to be Initiated on ART in FY24
    from the Cascade tab of the Target Setting Tool.

2.  Review and adjust CXCA_SCRN Coverage - Already on ART (FY25) (%) which
    will be defaulted to 33% and Coverage - Initiated on ART (FY25) (%) will
    be defaulted to 100%. 
    Determine the proportion of HIV positive women currently on treatment that will
    receive cervical cancer screening in COP2120/FY24 implementation
    year. Each team will have a default value of 50% set in this column
    as in past years. However, please follow COP21 Guidance and adjust
    to approximate full coverage of TX_NEW and 25% of already on ART,
    depending on prior year achievements and any additional country
    specific guidance from your Chair and PPM. To remove all FY25
    cervical cancer targets, set this column to 0%.

3.  Review FY25 targets for CXCA_SCRN and return to steps 1 and 2 to
    adjust. This target is set based on the number of eligible women in
    the COP 21 TX_CURR cohort multiplied by the Targeted CXCA Screening
    Coverage Rate.

\elandscape

\newpage
