---
editor_options: 
  markdown: 
    wrap: 72
---

\blandscape

# GEND

## GEND: GEND_GBV

**GEND_GBV:** Number of people receiving post-gender-based violence
(GBV) clinical care based on the minimum package.

```{r echo=FALSE, results='asis'}
sheet_name <- "GEND"
section <- "GEND_GBV"
columns <- col_seq("C", "H")
data <- prepare_table_data(sheet_name, columns)
for (t in table_seq(data, max_col = 3)) {
  make_table(t, section)
  }
```

### DATIM Import

The following data points will be imported into DATIM from this section:

-   **Physical/Emotional Violence (FY25)** $GEND\_GBV.PE.T$

-   **Sexual Violence (FY25)** $GEND\_GBV.S.T$

### Instructions

1.  For historical context, review FY23 targets for both the
    Physical/Emotional Violence and Sexual Violence service types, which
    are pre-populated from DATIM.

2.  Review and adjust the "Projected change in GEND_GBV -
    Physical/Emotional Violence services (%)" and "Projected change in
    GEND_GBV - Sexual Violence services (%)" columns. These will default
    to 0%, though this reflects no suggested strategic direction.

3.  Review FY25 targets for both the "Physical/Emotional Violence" and
    "Sexual Violence" service types. Each of these is calculated as a
    function of the expected change rate multiplied by the FY24 target
    for the related service type. In the case services are planned in
    FY25 where these were not provided in FY24, you may manually enter
    FY25 targets in these columns.

\elandscape

\newpage
