\blandscape

# KP_MAT

**KP_MAT:** Number of people who inject drugs (PWID) on medication-assisted therapy (MAT) for at least 6 months

```{r echo=FALSE, results='asis'}
sheet_name <- "KP_MAT"
section <- "KP_MAT"
columns <- col_seq("E", "K")
data <- prepare_table_data(sheet_name, columns)
for (t in table_seq(data, max_col = 4)) {
  make_table(t, section)
  }
```

### DATIM Import

The following data points will be imported into DATIM from this section:

-   **KP_MAT (FY25)** $KP\_MAT.T$

-   **Host Country KP_MAT_SUBNAT (FY25)** $KP\_MAT\_SUBNAT.T$

### Instructions

1.  Enter values for column "Host Country Estimated KP_MAT_SUBNAT (FY24)", as available. Sources for this data should be approved by the PPM and DUIT Liaison assigned to your Country.

2.  Review "PEPFAR KP_MAT (FY24 Targets)", pulled from DATIM as reference for historical context.

3.  Review Observed PEPFAR Coverage of KP_MAT_SUBNAT (FY24 Targets), calculated by dividing FY24 PEPFAR KP_MAT targets by Host Country Estimated KP_MAT_SUBNAT (FY24).

4.  Review "Targeted PEPFAR Coverage of KP_MAT_SUBNAT (FY25) (%)" which will pull directly from the previous column for FY23 that was calculated in the last step, but you may edit this as needed.

5.  Review and adjust "Targeted Growth in KP_MAT (FY25) (%)". This will be prepopulated at 0%, but you may adjust this as needed.

6.  Review "KP_MAT (FY25)" which will be the product of "PEPFAR KP_MAT (FY24 Targets)" multiplied against "Targeted Growth in KP_MAT (FY25) (%)". In the case services are planned in FY25 where these were not provided in FY24, you may manually enter FY25 targets in these columns.

7.  Review "Host Country KP_MAT_SUBNAT (FY25)" and adjust previous assumptions as needed. The Target Setting Tool will model these targets based upon FY25 PEPFAR KP_MAT targets and the Targeted PEPFAR Coverage of KP_MAT_SUBNAT (FY25) (%).

\elandscape

\newpage
