\blandscape

# Year 2 Targets

In an effort to help teams think through multi-year programmatic approach while setting detailed targets for the upcomign fiscal year. Year 2 targets will not be imported into DATIM and will only be set at a National Level with Age/Sex disaggregates. Teams should be aware that all final Year 2 (FY26) Targets are editable, and will not be imported to DATIM, but these will flow to the PAW - COP Dossier. 

With the unique nature of age bands for some indicators, users will need to scroll down to see the various rows that will contain these unique age bands. The main age bands and KP groups will be populated at the top of the tab, and the other age bands will appear below. Any age band that should not be used are greyed out and will not contain any data. 

### CASCADE

The Cascade Section will model the Year 2  (FY26) Target in a very similar manner to that of the Cascade tab. 

### Testing Distribution

The Testing Distribution will only look at the % used for FY24 and how they could relate for FY26, band this % will be the baseline for FY26 There are no HTS_TST_POS or HTS_TST_NEG to be set for FY26, only the PLHIV to Identify (HTS_TST_POS + PMTCT_HEI_POS) (FY26).

### All Other Indicators

All other MER Indicators will be set for FY26 The Year 2 tab will pull in the FY26 target from the main tabs and this will pre-populate the blue FY25 target column as a starting point in which teams can then adjust and add multipliers to set the Year 2 (FY26) Target.

\elandscape

\newpage
